# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock

input-field {
  monitor =
  fade_on_empty = false
  size = 250, 60
  outline_thickness = 2
  dots_size = 0.2
  dots_spacing = 0.35
  dots_center = true
  outer_color = rgba(0, 0, 0, 0)
  inner_color = rgba(0, 0, 0, 0.2)
  font_color = rgba(205, 214, 244, 1.0)
  fade_on_empty = false
  rounding = -1
  check_color = rgb(204, 136, 34)
  placeholder_text = <i><span foreground="##cdd6f4">Input Password...</span></i>
}

background {
  path = /home/Gary/Pictures/wallpaper/duhhh.jpg
  monitor =
  blur_passes = 0
  blur_size = 10
  contrast = 1
  brightness = 0.5
  vibrancy = 0.2
  vibrancy_darkness = 0.2
#  color = rgba(0,0,0,0.0)
#  blur_passes = 0
}

general {
  hide_cursor = false
  grace = 0
#  immediate_render = true
  disable_loading_bar = true
}

# Date

label {
  monitor = 
  text = cmd[update:1000] date +"%A, %B %d"
  color = rgba(242, 243, 244, 0.75)
  font_size = 22
  font_family = JetBrains Mono
  position = 0, 300
  halign = center
  valign = center
}

# Time

label {
  monitor = 
  text = cmd[update:1000] date +"%-I:%M"
  color = rgba(242, 243, 244, 0.75)
  font_size = 95
  font_family = JetBrains Mono Extrabold
  position = 0, 200
  halign = center
  valign = center
}

# Profile Picture
image {
  monitor = 
  path = /home/Gary/Pictures/pfp/silly.jpg
  size = 200
  border_size = 2
  border_color = rgba(221, 221, 221, 1.0)
  position = 0, -200
  halign = center
  valign = center
}
animations {
  enabled = false
}
